const options = [
  {
    label: 'Afrikaans',
    value: 'af'
  },
  {
    label: 'Arabic',
    value: 'ar'
  },
  {
    label: 'Hindi',
    value: 'hi'
  }
];
// const options = [
// { value: 'af', value: 'Afrikaans' },
// { value: 'sq', value: 'Albanian' },
// { value: ‘am’, value: ‘Amharic’ },
// { value: ‘ar’, value: ‘Arabic’ },
// { value: ‘hy’, value: ‘Armenian’ },
// { value: ‘az’, value: ‘Azerbaijani’ },
// { value: ‘eu’, value: ‘Basque’ },
// { value: ‘be’, value: ‘Belarusian’ },
// { value: ‘bn’, value: ‘Bengali’ },
// { value: ‘bs’, value: ‘Bosnian’ },
// { value: ‘bg’, value: ‘Bulgarian’ },
// { value: ‘ca’, value: ‘Catalan’ },
// { value: ‘ceb’, value: ‘Cebuano’ },
// { value: ‘ny’, value: ‘Chichewa’ },
// { value: ‘zh’, value: ‘Chinese (Simplified)’ },
// { value: ‘zh-TW’, value: ‘Chinese (Traditional)’ },
// { value: ‘co’, value: ‘Corsican’ },
// { value: ‘hr’, value: ‘Croatian’ },
// { value: ‘cs’, value: ‘Czech’ },
// { value: ‘da’, value: ‘Danish’ },
// { value: ‘nl’, value: ‘Dutch’ },
// { value: ‘en’, value: ‘English’ },
// { value: ‘eo’, value: ‘Esperanto’ },
// { value: ‘et’, value: ‘Estonian’ },
// { value: ‘tl’, value: ‘Filipino’ },
// { value: ‘fi’, value: ‘Finnish’ },
// { value: ‘fr’, value: ‘French’ },
// { value: ‘fy’, value: ‘Frisian’ },
// { value: ‘gl’, value: ‘Galician’ },
// { value: ‘ka’, value: ‘Georgian’ },
// { value: ‘de’, value: ‘German’ },
// { value: ‘el’, value: ‘Greek’ },
// { value: ‘gu’, value: ‘Gujarati’ },
// { value: ‘ht’, value: ‘Haitian Creole’ },
// { value: ‘ha’, value: ‘Hausa’ },
// { value: ‘haw’, value: ‘Hawaiian’ },
// { value: ‘iw’, value: ‘Hebrew’ },
// { value: ‘hi’, value: ‘Hindi’ },
// { value: ‘hmn’, value: ‘Hmong’ },
// { value: ‘hu’, value: ‘Hungarian’ },
// { value: ‘is’, value: ‘Icelandic’ },
// { value: ‘ig’, value: ‘Igbo’ },
// { value: ‘id’, value: ‘Indonesian’ },
// { value: ‘ga’, value: ‘Irish’ },
// { value: ‘it’, value: ‘Italian’ },
// { value: ‘ja’, value: ‘Japanese’ },
// { value: ‘jw’, value: ‘Javanese’ },
// { value: ‘kn’, value: ‘Kannada’ },
// { value: ‘kk’, value: ‘Kazakh’ },
// { value: ‘km’, value: ‘Khmer’ },
// { value: ‘rw’, value: ‘Kinyarwanda’ },
// { value: ‘ko’, value: ‘Korean’ },
// { value: ‘ku’, value: ‘Kurdish (Kurmanji)’ },
// { value: ‘ky’, value: ‘Kyrgyz’ },
// { value: ‘lo’, value: ‘Lao’ },
// { value: ‘la’, value: ‘Latin’ },
// { value: ‘lv’, value: ‘Latvian’ },
// { value: ‘lt’, value: ‘Lithuanian’ },
// { value: ‘lb’, value: ‘Luxembourgish’ },
// { value: ‘mk’, value: ‘Macedonian’ },
// { value: ‘mg’, value: ‘Malagasy’ },
// { value: ‘ms’, value: ‘Malay’ },
// { value: ‘ml’, value: ‘Malayalam’ },
// { value: ‘mt’, value: ‘Maltese’ },
// { value: ‘mi’, value: ‘Maori’ },
// { value: ‘mr’, value: ‘Marathi’ },
// { value: ‘mn’, value: ‘Mongolian’ },
// { value: ‘my’, value: ‘Myanmar (Burmese)’ },
// { value: ‘ne’, value: ‘Nepali’ },
// { value: ‘no’, value: ‘Norwegian’ },
// { value: ‘or’, value: ‘Odia (Oriya)’ },
// { value: ‘ps’, value: ‘Pashto’ },
// { value: ‘fa’, value: ‘Persian’ },
// { value: ‘pl’, value: ‘Polish’ },
// { value: ‘pt’, value: ‘Portuguese’ },
// { value: ‘pa’, value: ‘Punjabi’ },
// { value: ‘ro’, value: ‘Romanian’ },
// { value: ‘ru’, value: ‘Russian’ },
// { value: ‘sm’, value: ‘Samoan’ },
// { value: ‘gd’, value: ‘Scots Gaelic’ },
// { value: ‘sr’, value: ‘Serbian’ },
// { value: ‘st’, value: ‘Sesotho’ },
// { value: ‘sn’, value: ‘Shona’ },
// { value: ‘sd’, value: ‘Sindhi’ },
// { value: ‘si’, value: ‘Sinhala’ },
// { value: ‘sk’, value: ‘Slovak’ },
// { value: ‘sl’, value: ‘Slovenian’ },
// { value: ‘so’, value: ‘Somali’ },
// { value: ‘es’, value: ‘Spanish’ },
// { value: ‘su’, value: ‘Sundanese’ },
// { value: ‘sw’, value: ‘Swahili’ },
// { value: ‘sv’, value: ‘Swedish’ },
// { value: ‘tg’, value: ‘Tajik’ },
// { value: ‘ta’, value: ‘Tamil’ },
// { value: ‘tt’, value: ‘Tatar’ },
// { value: ‘te’, value: ‘Telugu’ },
// { value: ‘th’, value: ‘Thai’ },
// { value: ‘tr’, value: ‘Turkish’ },
// { value: ‘tk’, value: ‘Turkmen’ },
// { value: ‘uk’, value: ‘Ukrainian’ },
// { value: ‘ur’, value: ‘Urdu’ },
// { value: ‘ug’, value: ‘Uyghur’ },
// { value: ‘uz’, value: ‘Uzbek’ },
// { value: ‘vi’, value: ‘Vietnamese’ },
// { value: ‘cy’, value: ‘Welsh’ },
// { value: ‘xh’, value: ‘Xhosa’ },
// { value: ‘yi’, value: ‘Yiddish’ },
// { value: ‘yo’, value: ‘Yoruba’ },
// { value: ‘zu’, value: ‘Zulu’ }
// ]

export default options;